{{- if .Values.bff.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sdm.bff.fullname" . }}-secret
  labels:
    {{- include "sdm.bff.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.bff.secret }}
  {{ $k }}: {{ default "" $v | quote }}
  {{- end }}
{{- end }}
